package br.com.knowledgeislands.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

import br.com.knowledgeislands.utils.KnowledgeIslandsUtils;

@Service
public class EmailService {

	@Autowired
	private JavaMailSender mailSender;
	@Value("${configuration.app.send.email.devs}")
	private boolean sendEmail;

	public void sendEmail(String to, String subject, String body) {
		SimpleMailMessage message = new SimpleMailMessage();
		message.setTo(to);
		message.setSubject(subject);
		message.setText(body);
		if(sendEmail) {
			mailSender.send(message);
		}
	}

	public String getSubjectEmailSurveyGenAI() {
		return KnowledgeIslandsUtils.SUBJECT_EMAIL_SURVEY_GENAI;
	}

	public String getTextEmailSurveyGenAIRawText(String devName) {
		return """
				Dear %s,

				My name is Otávio Cury. I am a software engineering researcher at the Federal University of Piauí, Brazil. My <a href="https://scholar.google.com.br/citations?user=bTz_EPcAAAAJ">Google Scholar</a> profile provides more information about my work.

				My development team is investigating the impact of generative AI on developers' understanding of the source code they integrate into their projects. In this context, this survey aims to understand how developers incorporate code generated by generative AI into their projects and whether using these tools affects their understanding of the integrated code.

				<b>We also emphasize that all data collected will be anonymized in future research publications and used exclusively for academic purposes.</b>

				Question 1: How do you typically integrate code generated by ChatGPT into your projects?<br>
				A) I integrate the generated code with minimal scrutiny, primarily ensuring it works (e.g., it compiles/runs without a detailed review).<br>
				B) I integrate the generated code with a general understanding (e.g., understanding its inputs and outputs but not all internal logic).<br>
				C) I integrate the generated code with a detailed understanding (e.g., reviewing it line-by-line and fully understanding its implementation).<br>

				Question 2: Do you take additional steps to learn from the code generated by ChatGPT (e.g., researching concepts or exploring alternative implementations)?<br>
				A) Never<br>
				B) Rarely<br>
				C) Sometimes<br>
				D) Often<br>
				E) Always<br>

				Question 3: Do you believe using ChatGPT as a code assistant affects your understanding of the integrated code?<br>
				A) Negatively<br>
				B) No impact<br>
				C) Positively<br>
				D) Not sure<br>

				Follow-up: Please explain your answer to Question 3 (e.g., it helps you learn, speeds up work, decreases understanding, etc.).

				We appreciate your time and insights, which will contribute significantly to this research.

				Best regards,<br>
				Otávio Cury<br>
				Software Engineering Researcher<br>
				Federal University of Piauí, Brazil
				""".formatted(devName);
	}

	public String getTextEmailSurveyGenAIGoogleForm(String devName) {
		return """
				Dear %s,

				My name is Otávio Cury. I am a software engineering researcher at the Federal University of Piauí, Brazil. My <a href="https://scholar.google.com.br/citations?user=bTz_EPcAAAAJ">Google Scholar</a> profile provides more information about my work.

				My development team is investigating the impact of generative AI on developers' understanding of the source code they integrate into their projects. In this context, this survey aims to understand how developers incorporate code generated by generative AI into their projects and whether using these tools affects their understanding of the integrated code.

				<b>We also emphasize that all data collected will be anonymized in future research publications and used exclusively for academic purposes.</b>

				Here is the link to the Google form with the survey: https://forms.gle/ifKtMnAxoxzZj4RY9<br>

				We appreciate your time and insights, which will contribute significantly to this research.

				Best regards,<br>
				Otávio Cury<br>
				Software Engineering Researcher<br>
				Federal University of Piauí, Brazil
				""".formatted(devName);
	}

}
